"""update auth model

Revision ID: bdc1a18d76d7
Revises: 997832ea1517
Create Date: 2026-07-02 12:40:27.284742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bdc1a18d76d7'
down_revision: Union[str, Sequence[str], None] = '997832ea1517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('image_public_id', sa.String(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'USER', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'USER', name='userrole'),
               nullable=False)
    op.drop_column('users', 'image_public_id')
    op.drop_column('users', 'image_url')
    # ### end Alembic commands ###
